### ISSUE TITLE
Focus catched by stackoverflow

### ISSUE THREAD

**Issue by dynobo** [BrainMaestro/cerebro-stackoverflow#4] opened 2017-02-25 12:05 UTC
Not quite sure, if this a cerebro core issue, but as it only happens to me with the stackoverflow plugin, here might be the right place.

Cerebro 0.2.6, Cerebro-Stackoverflow 0.5.0, on Arch Linux

**Problem:**

 If I start typing something, as soon as there is no other result in the application index, Stackoverflow-Plugin takes over and starts its search, even if i'm not finished typing. 

What it does make it worth: it then also catches the focus from the search field (search gets inactive), so I have to hit "Esc" to get back to the search field and finish my typing.

**Proposial:**
* Don't catch the focus from search field. Wait until the User hit's enter or something.
* Make search more lazy, waiting for Enter or 0.5sec after last keystroke, before search in Stackoverflow.

**Demo Gif:**
![peek 2017-02-25 13-02](https://cloud.githubusercontent.com/assets/11071876/23330873/be1efbe8-fb5a-11e6-85ba-541f29787d21.gif)

**Comment by BrainMaestro** [comment] 2017-02-25 18:09
Hey @dynobo. I'll take a look at it, thanks for reporting. The issue is probably related to the keyboard support that was recently added.

**Comment by BrainMaestro** [comment] 2017-02-25 23:11
`v0.5.1` should solve the first issue you had which is automatically taking focus. 

The second one which is starting the search even when you haven't finished typing is a cerebro issue. It just passes the search term into the plugins. There's no way for me to tell if the user is done typing. Maybe you should open an issue in the cerebro repo?

I'll close this issue now, but if the focus problem reoccurs, feel free to open it again. 
Thanks

**Closed as completed by BrainMaestro** 2017-02-25 23:11 UTC
